include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Remove the unrecognized error code
    missing_required_param: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false